/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tshirt.glb 
Author: funlab117 (https://sketchfab.com/funlab117)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-c1a3e5eb9b5445f4b7d4be82f1127eba
Title: T Shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.661, 0.003, -0.504]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Body_FRONT_2664} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Sleeves_FRONT_2669} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Sleeves_FRONT_2669} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tshirt.glb')
